[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
processing_instructions = "ESFoo5N4Zv65pph6thqP3HVqiY7KH5o5V8TqTsnmB2vw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
